# Generated by Django 5.2.14 on 2026-06-09 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código UUID (para QR)')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del mobiliario/equipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o número de serie')),
                ('estado', models.CharField(choices=[('bueno', 'Excelente / Bueno'), ('regular', 'Regular / Desgastado'), ('malo', 'Dañado / Requiere cambio')], default='bueno', max_length=15, verbose_name='Estado físico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('stand_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_inventario', to='espacios.stand', verbose_name='Stand asignado')),
            ],
            options={
                'verbose_name': 'Mobiliario / Item de Inventario',
                'verbose_name_plural': 'Mobiliarios / Items de Inventario',
                'ordering': ['nombre', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del problema')),
                ('descripcion', models.TextField(verbose_name='Detalle de la incidencia')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta / Crítica')], default='media', max_length=10, verbose_name='Prioridad')),
                ('resuelta', models.BooleanField(default=False, verbose_name='¿Incidencia resuelta?')),
                ('comentarios_resolucion', models.TextField(blank=True, verbose_name='Comentarios de resolución')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='inventario.iteminventario', verbose_name='Mobiliario afectado')),
            ],
            options={
                'verbose_name': 'Incidencia de Inventario',
                'verbose_name_plural': 'Incidencias de Inventario',
                'ordering': ['resuelta', '-fecha_reporte'],
            },
        ),
    ]
