# Generated by Django 5.2.14 on 2026-06-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_rename_alumno_creador_proyecto_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número / Identificador del Stand')),
                ('zona', models.CharField(choices=[('gimnasio', 'Gimnasio UTEQ'), ('auditorio', 'Auditorio principal'), ('pasillo_a', 'Pasillo Edificio A'), ('pasillo_b', 'Pasillo Edificio B'), ('exterior', 'Explanada / Exterior'), ('otro', 'Otro / Sala alterna')], default='gimnasio', max_length=20, verbose_name='Zona física')),
                ('capacidad_proyectos', models.PositiveIntegerField(default=1, verbose_name='Capacidad de proyectos simultáneos')),
                ('descripcion', models.TextField(blank=True, verbose_name='Detalles adicionales del espacio')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Disponible para asignación')),
            ],
            options={
                'verbose_name': 'Stand / Espacio',
                'verbose_name_plural': 'Stands / Espacios',
                'ordering': ['zona', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios de asignación')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_stands', to='usuarios.proyecto', verbose_name='Proyecto asignado')),
                ('stand', models.OneToOneField(limit_choices_to={'esta_activo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='espacios.stand', verbose_name='Stand / Mesa física')),
            ],
            options={
                'verbose_name': 'Asignación de Stand',
                'verbose_name_plural': 'Asignaciones de Stands',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
