# Generated by Django 5.2.14 on 2026-06-09 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_grupo', models.CharField(max_length=10, verbose_name='Código del Grupo a evaluar')),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'EVALUADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_impartidos', to=settings.AUTH_USER_MODEL, verbose_name='Docente Evaluador')),
            ],
            options={
                'verbose_name': 'Carga Académica Docente',
                'verbose_name_plural': 'Cargas Académicas de Docentes',
                'constraints': [models.UniqueConstraint(fields=('docente', 'codigo_grupo'), name='unique_grupo_por_docente')],
            },
        ),
    ]
