# Generated by Django 5.2.14 on 2026-06-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_cargadocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='pos_col',
            field=models.PositiveIntegerField(default=0, verbose_name='Posición Columna (Coordenada X)'),
        ),
        migrations.AddField(
            model_name='stand',
            name='pos_fila',
            field=models.PositiveIntegerField(default=0, verbose_name='Posición Fila (Coordenada Y)'),
        ),
    ]
