# Generated by Django 5.2.14 on 2026-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0003_stand_pos_col_stand_pos_fila'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionstand',
            name='cambio_autorizado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cambio autorizado por admin'),
        ),
        migrations.AddField(
            model_name='asignacionstand',
            name='cambio_solicitado',
            field=models.BooleanField(default=False, verbose_name='Cambio solicitado por alumno'),
        ),
        migrations.AddField(
            model_name='asignacionstand',
            name='motivo_cambio',
            field=models.TextField(blank=True, verbose_name='Motivo de solicitud de cambio'),
        ),
        migrations.AddField(
            model_name='asignacionstand',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='Motivo de rechazo de cambio'),
        ),
    ]
