# Generated by Django 5.2.14 on 2026-08-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0004_asignacionstand_cambio_autorizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionstand',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Asignación activa'),
        ),
        migrations.AlterField(
            model_name='asignacionstand',
            name='stand',
            field=models.ForeignKey(limit_choices_to={'esta_activo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='espacios.stand', verbose_name='Stand / Mesa física'),
        ),
    ]
