# Generated by Django 5.2.14 on 2026-08-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0005_asignacionstand_activa_alter_asignacionstand_stand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionstand',
            name='stand',
            field=models.OneToOneField(blank=True, limit_choices_to={'esta_activo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignacion', to='espacios.stand', verbose_name='Stand / Mesa física'),
        ),
    ]
