# Generated by Django 5.2.14 on 2026-06-02 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción o Resumen')),
                ('integrantes', models.TextField(help_text='Nombres de los integrantes separados por comas', verbose_name='Integrantes')),
                ('estatus', models.CharField(choices=[('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='revision', max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Calificación Final')),
                ('comentarios_evaluador', models.TextField(blank=True, null=True, verbose_name='Comentarios del Profesor')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
