# Generated by Django 5.2.14 on 2026-06-03 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(choices=[('software', 'Desarrollo de Software'), ('hardware', 'Hardware / Electrónica'), ('redes', 'Redes y Telecomunicaciones'), ('ia', 'Inteligencia Artificial'), ('otro', 'Otro')], default='software', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='evaluador_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'EVALUADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_a_evaluar', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador Asignado'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='grupo',
            field=models.CharField(blank=True, help_text='Ej: "A", "4B"', max_length=10, verbose_name='Grupo / Paralelo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='integrantes',
            field=models.TextField(blank=True, help_text='Nombres de los integrantes separados por comas', verbose_name='Integrantes (texto)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='usuarios.carrera', verbose_name='Carrera'),
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('matricula', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Institucional')),
                ('es_lider', models.BooleanField(default=False, verbose_name='¿Es líder?')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='usuarios.proyecto')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['-es_lider', 'nombre_completo'],
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'matricula'), name='unique_matricula_por_proyecto')],
            },
        ),
    ]
