# Generated by Django 5.2.14 on 2026-06-03 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_carrera_alter_proyecto_options_proyecto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentarios_evaluador', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='integrante',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='integrante',
            name='unique_matricula_por_proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='alumno_creador',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='integrantes',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_proyectos/'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='es_lider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='matricula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='nombre_completo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='usuarios.proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='carrera',
            field=models.CharField(choices=[('DSM', 'Desarrollo de Software Multiplataforma'), ('ITI', 'Ingeniería en Tecnologías de la Información'), ('REDES', 'Redes Digitales y Ciberseguridad')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(choices=[('PROTOTIPO', 'Prototipo Tecnológico'), ('INVESTIGACION', 'Investigación Académica'), ('INNOVACION', 'Innovación y Emprendimiento')], default='PROTOTIPO', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='comentarios_evaluador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(choices=[('REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='APROBADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='evaluador_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='grupo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='usuarios.proyecto'),
        ),
    ]
