# Generated by Django 5.2.14 on 2026-06-04 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_evaluacion_alter_integrante_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='integrante',
            options={'ordering': ['-es_lider', 'nombre_completo'], 'verbose_name': 'Integrante', 'verbose_name_plural': 'Integrantes'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='comentarios_evaluador',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='estatus_sugerido',
            field=models.CharField(choices=[('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='aprobado', max_length=20, verbose_name='Resultado sugerido'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='evaluador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='alumno_creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL, verbose_name='Alumno / Creador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Institucional'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='es_lider',
            field=models.BooleanField(default=False, verbose_name='¿Es líder?'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='matricula',
            field=models.CharField(max_length=20, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='nombre_completo',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='usuarios.proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Calificación Final'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='usuarios.carrera', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(choices=[('software', 'Desarrollo de Software'), ('hardware', 'Hardware / Electrónica'), ('redes', 'Redes y Telecomunicaciones'), ('ia', 'Inteligencia Artificial'), ('otro', 'Otro')], default='software', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción o Resumen'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estatus',
            field=models.CharField(choices=[('revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='revision', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='evaluador_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'EVALUADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_a_evaluar', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador Asignado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='grupo',
            field=models.CharField(blank=True, max_length=10, verbose_name='Grupo / Paralelo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del Proyecto'),
        ),
        migrations.AddConstraint(
            model_name='evaluacion',
            constraint=models.UniqueConstraint(fields=('proyecto', 'evaluador'), name='unique_evaluacion_por_evaluador'),
        ),
        migrations.AddConstraint(
            model_name='integrante',
            constraint=models.UniqueConstraint(fields=('proyecto', 'matricula'), name='unique_matricula_por_proyecto'),
        ),
    ]
