# Generated by Django 5.2.14 on 2026-06-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_evaluacion_options_alter_integrante_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='alumno_creador',
            new_name='creado_por',
        ),
    ]
