# Generated by Django 5.2.14 on 2026-06-16 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_alumno_creador_proyecto_creado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del criterio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o rúbrica de desempeño')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en decimal (ej. 0.35 para 35%). La suma de los criterios activos debe ser 1.00', max_digits=3, verbose_name='Peso del criterio')),
                ('activo', models.BooleanField(default=True, verbose_name='Criterio activo')),
            ],
            options={
                'verbose_name': 'Criterio de Evaluación',
                'verbose_name_plural': 'Criterios de Evaluación',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_cualitativa', models.CharField(choices=[('AU', 'Autónomo (10)'), ('DE', 'Destacado (9)'), ('SA', 'Satisfactorio (8)'), ('NA', 'No Aprobatorio (0)')], max_length=2, verbose_name='Evaluación cualitativa')),
                ('calificacion_numerica', models.DecimalField(decimal_places=2, editable=False, max_digits=4, verbose_name='Calificación numérica')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_evaluacion', to='usuarios.criterioevaluacion')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='usuarios.evaluacion')),
            ],
            options={
                'verbose_name': 'Detalle de Evaluación',
                'verbose_name_plural': 'Detalles de Evaluación',
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'criterio'), name='unique_criterio_por_evaluacion')],
            },
        ),
    ]
