# Generated by Django 5.2.14 on 2026-06-22 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_criterioevaluacion_alter_evaluacion_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='comentarios_evaluador',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='EvaluacionExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=150)),
                ('empresa_procedencia', models.CharField(max_length=150)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('calificacion', models.CharField(choices=[('AU', 'AU - Autónomo (10)'), ('DE', 'DE - Destacado (9)'), ('SA', 'SA - Satisfactorio (8)'), ('NA', 'NA - No Acreditado')], max_length=2)),
                ('comentario', models.TextField(blank=True)),
                ('codigo_acceso_usado', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_externas', to='usuarios.proyecto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
