# Generated by Django 5.2.14 on 2026-06-22 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_proyecto_comentarios_evaluador_evaluacionexterna'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('login_fallido', 'Intento fallido de login'), ('2fa_exitoso', 'Verificación 2FA exitosa'), ('2fa_fallido', 'Verificación 2FA fallida'), ('registro', 'Registro de usuario'), ('cambio_estatus', 'Cambio de estatus de proyecto'), ('evaluacion', 'Evaluación registrada'), ('evaluacion_externa', 'Evaluación externa registrada'), ('resolucion_incidencia', 'Incidencia resuelta')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de actividad',
                'verbose_name_plural': 'Logs de actividad',
                'ordering': ['-fecha'],
            },
        ),
    ]
