# Generated by Django 5.2.14 on 2026-06-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_logactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='qr_evaluacion_externa',
            field=models.ImageField(blank=True, null=True, upload_to='qr_proyectos/', verbose_name='QR de evaluación externa'),
        ),
    ]
