# Generated by Django 5.2.14 on 2026-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_criterios_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='mesas_autorizadas',
            field=models.BooleanField(default=False, verbose_name='Mesas extra autorizadas por admin'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='mesas_requeridas',
            field=models.PositiveIntegerField(choices=[(1, '1 mesa (estándar)'), (2, '2 mesas (proyecto con equipo grande o prototipo físico)'), (3, '3 mesas (instalación especial — requiere autorización del admin)')], default=1, verbose_name='Mesas requeridas para exhibición'),
        ),
    ]
