# Generated by Django 5.2.14 on 2026-08-15 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_proyecto_mesas_autorizadas_proyecto_mesas_requeridas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='evaluador_asignado',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='evaluadores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'EVALUADOR'}, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Evaluadores asignados'),
        ),
    ]
