# Generated by Django 5.2.14 on 2026-08-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_proyecto_evaluador_asignado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='calificacion',
            new_name='calificacion_final',
        ),
        migrations.RenameField(
            model_name='evaluacion',
            old_name='comentarios_evaluador',
            new_name='comentarios',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='calificacion',
            new_name='calificacion_final',
        ),
    ]
